### ISSUE TITLE
Theme issue with PowerToys run after installing the plugin

### ISSUE THREAD

**Issue by some-sh** [Advaith3600/PowerToys-Run-Currency-Converter#10]
After installing the plugin, the theme is a little different than it used to be. 

Before installing plugin:
![image](https://github.com/Advaith3600/PowerToys-Run-Currency-Converter/assets/31799333/733ef0aa-f3ba-4eb9-be22-ae42b1520cbb)

After installing plugin:
![image](https://github.com/Advaith3600/PowerToys-Run-Currency-Converter/assets/31799333/4c7adeef-930a-41fc-b833-8b69567deb3d)

Notice the background/theme/color scheme of the search result or whatever it is called. 

While it is not a big problem in itself, but I'd like it if the theme or the colors are not changed

I don't have a good knowledge about C# or .NET but upon looking the code, couldn't find a reason why this is happening. I thought of building one myself having this plugin as a reference but since I couldn't find why this is happening, I didn't proceed further

I'd like if this issue is fixed and released because this is really useful and handy

**Comment by Advaith3600** [comment]
Hey, thanks for bringing this to my attention, I have noticed the same with my PC, but it doesn't have the issue on my work PC. I thought it might be some glitch due to the Power Toys update, but this could be a build issue. I will have a look into it. Please give me details about the versions of the plugin and power toys that you have currently installed in the meantime.

**Comment by some-sh** [comment]
PowerToys version: 0.81.1
Plugin version: 1.1.4

I restarted my machine this morning for a different reason, now the issue doesn't seem to exist. PFA

![image](https://github.com/Advaith3600/PowerToys-Run-Currency-Converter/assets/31799333/cad909f2-39bb-40a7-b392-f983f673b567)

**Comment by Advaith3600** [comment]
I believe a rebuild with updated DLL files will solve this issue, since you are not having the issue anymore, I will do the update with other things I am working on. 

I am closing this issue for now. If you have any more issues please open it or create a new one.
