### ISSUE TITLE
"Invalid expression provided"

### ISSUE THREAD

**Issue by dero** [Advaith3600/PowerToys-Run-Currency-Converter#13]
I would like to use the plugin with "Include in global result" enabled, but the plugin very often outputs the "Invalid expression provided (Please check your mathematical expression)" list item, which I don't want to see.

![image](https://github.com/Advaith3600/PowerToys-Run-Currency-Converter/assets/433570/4caad95d-fbc2-4ed1-95e5-331b356c8545)

Ideally there should be a setting to either suppress this message. I don't want the plugin nagging me that unrelated input is not something it can convert.

**Comment by Advaith3600** [comment]
I have always used the include in the global result and never bothered by the message, but I can see how it can be unpleasant. I will add an option to suppress warnings in the next version release.

**Comment by dero** [comment]
@Advaith3600 Thank you! That will be very much appreciated.

**Comment by Advaith3600** [comment]
![image](https://github.com/Advaith3600/PowerToys-Run-Currency-Converter/assets/21041099/5487b17c-47df-463b-9c84-837fd7e40eb5)

Does it make sense to suppress this warning as well? To me, that would be annoying to know that I mistyped the currency and not get an error. What do you think?

**Comment by dero** [comment]
@Advaith3600 Well, I think the plugin should not emit any error messages if it can't handle the input in the global search, because you can't really tell that the user is expecting a currency conversion. And if you don't know user's intent, it's potentially annoying to insert error message into their results. It's as if the "Folder" plugin inserted "No such directory" into your results, for example.

However, the plugin should absolutely emit these messages when the activation command is prepended. In that case it's clear the user expects currency conversion.

Plus, I doubt many people routinely convert between many currencies. I think people usually just convert between a few, and they won't really make many mistakes typing "USD" or "BTC".

So ultimately I think the default should be:

- No error messages in global results.
- Existing error messages when activation command is used.

And for people who like to fine tune things I'd probably add a setting when "Include in global result" is enabled:

- "Show error messages in global result"

**Comment by Advaith3600** [comment]
Hi, I got busy with other work, but I finally implemented this. I want to get your opinion before I publish this. Please let me know your thoughts. 

[CurrencyConverter-1.1.5-x64.zip](https://github.com/user-attachments/files/16282582/CurrencyConverter-1.1.5-x64.zip)
[CurrencyConverter-1.1.5-ARM64.zip](https://github.com/user-attachments/files/16282583/CurrencyConverter-1.1.5-ARM64.zip)

**Comment by dero** [comment]
@Advaith3600 LGTM – behaves as I'd expect it to. 🎉
