### ISSUE TITLE
Using "in" in query

### ISSUE THREAD

**Issue by vaner-org** [Advaith3600/PowerToys-Run-Currency-Converter#16]
Hi, just making the suggestion to include "in" like "50 USD in CAD"

I often find myself trying to use it because of Spotlight muscle memory.

**Comment by Advaith3600** [comment]
Hi, thanks for the idea, but unfortunately I am traveling and do not have access to a Windows PC for the next couple of weeks. But, if you could modify the code and build it yourself you could get this feature. 

You will have to modify the regex from https://github.com/Advaith3600/PowerToys-Run-Currency-Converter/blob/314a300540ef2fad155ce1581bdecd7d36b76033/Community.PowerToys.Run.Plugin.CurrencyConverter/Main.cs#L363

to something like

```
@"^\s*(?:(?:(?<amount>[0-9.,+\-*/ \(\)]+)\s*(?<from>\w*))|(?:(?<from>[a-zA-Z]*)\s*(?<amount>[0-9.,+\-*/ \(\)]+)))\s*(?:to|in)?\s*(?<to>\w*)\s*$"
```

**Comment by vaner-org** [comment]
Thank you! I'll try this out.

**Comment by Advaith3600** [comment]
[CurrencyConverter-1.2.0-ARM64.zip](https://github.com/user-attachments/files/17072485/CurrencyConverter-1.2.0-ARM64.zip)
[CurrencyConverter-1.2.0-x64.zip](https://github.com/user-attachments/files/17072488/CurrencyConverter-1.2.0-x64.zip)

I have added the functionality here. You use this until the next version is released.
