### ISSUE TITLE
Files in the release zip archive

### ISSUE THREAD

**Issue by hlaueriksson** [Advaith3600/PowerToys-Run-Currency-Converter#2]
Some files in the release zip archive, `currency-converter.zip` `v1.0.1`, is unnecessary:

- `PowerToys.Common.UI.dll`
- `PowerToys.ManagedCommon.dll`
- `PowerToys.Settings.UI.Lib.dll`
- `Wox.Infrastructure.dll`
- `Wox.Plugin.dll`

**Comment by Advaith3600** [comment]
Thanks for the input. I have removed all the unwanted files from the build. 🎉
