### ISSUE TITLE
Option to add more currencies.

### ISSUE THREAD

**Issue by AstudilloMarillo** [Advaith3600/PowerToys-Run-Currency-Converter#4]
I'd like the option to add more currencies that immediately show up in the results.

**Comment by Advaith3600** [comment]
Hi there! Just wanted to let you know that we are currently using the API provided by [Exchange API](https://github.com/fawazahmed0/exchange-api) for this project. If you're interested in adding new currencies, please feel free to open a PR there. However, please note that we don't have any plans to add the option to add currencies directly to the plugin at this time.

**Comment by AstudilloMarillo** [comment]
Oh, I see how you interpreted this. My wording was all wrong. I was not talking about custom currencies, I meant the amount of currencies that the plugin shows.

Right now, you can have 2 (1 local and 1 global). I would like to be able to have more (I guess global would make the most sense) currencies.

I hope this is clearer. Sorry for the confusion.

**Comment by Advaith3600** [comment]
That is an interesting idea, I would like to add that, I am currently traveling and I don't have my PC with Windows available to me right now, I will work on this as soon as I get back. I am not sure if Powertoys Run plugins support multiple selection dropdowns, have to check how I can do this without just spamming more fields into the UI.

**Comment by AstudilloMarillo** [comment]
Great! Looking forward to it :)

**Comment by Advaith3600** [comment]
[CurrencyConverter-1.1.0-x64.zip](https://github.com/Advaith3600/PowerToys-Run-Currency-Converter/files/14852745/CurrencyConverter-1.1.0-x64.zip)

It would be great to get your opinion on this. I have added a text field where you can add extra currencies, which will be used for the quick conversions.

**Comment by AstudilloMarillo** [comment]
Other than that BTC is not working, it seems like exactly what I was thinking! Thanks for adding this.

Using this new method does make one of the "Quick Convertion (local or global) Currency" options obsolete imo, but I found that when I leave one blank it defaults to USD.

I would personally want to use this plugin like this:
-Fill in the currency I use most as 'Local Currency'
-Leave 'Global Currency' blank
-Fill all other currencies I'm interested in into the new 'Extra currencies for quick conversion' field
-Now the result is a quick list of all currencies I'm interested in compared to my Local Currency, I never have to think about filling in whatever currency I want to convert to again, since all my relevant options show up every time.

The only thing missing then is a method to on-the-fly invert the 'Quick Convertion Direction' (maybe this could trigger when you start your number with a minus(-) sign, or maybe there's a better way)

I know this turned into a-whole-nother feature request, hope that's okay. Just wanted to share my personal vision for a perfect currency converter!..

**Comment by Advaith3600** [comment]
Thank you for your suggestion. I am always open to more ideas. 

I am closing this issue as it is resolved and I have published a new version at https://github.com/Advaith3600/PowerToys-Run-Currency-Converter/releases/tag/v1.1.1
