### ISSUE TITLE
On-the-fly Convertion Direction invertion

### ISSUE THREAD

**Issue by AstudilloMarillo** [Advaith3600/PowerToys-Run-Currency-Converter#5]
Most of the time, I'm happy with the Quick Convertion Direction setting I set, but sometimes, I want it the other way around. It's a hassle to go into the PowerToys settings to change it, only to have to change it back once I'm done with my search.

I'd love being able to invert the convertion direction on-the-fly. I'm not 100% sure what the most intuitive way to use it is, but my suggestion is to precede your number amount with a minus(-) sign.

So say that my normal Quick Convertion Direction would be set to 'From local to global' and my local currency is EUR and global is USD, doing a normal search like: "$ 100" would give me a currency conversion of EUR to USD. When I would do a search like this: "$ -100" would give me a currency conversion of USD to EUR.

Hope this makes sense, love the latest update, this is already the best currency converter I've used.

**Comment by Advaith3600** [comment]
As a programmer, `!` makes more sense for inverting something. eg: `!100`. 
It will take some time for me to implement this as I am traveling again. I am also planning to add support for mathematical expressions.

**Comment by AstudilloMarillo** [comment]
> As a programmer, `!` makes more sense for inverting something. eg: `!100`.

Great! Sounds good to use `!`

> It will take some time for me to implement this as I am traveling again. I am also planning to add support for mathematical expressions.

Take all the time you need, save journeys. Curious to see what the mathematical expressions will bring.

**Comment by tMaxx** [comment]
I've seen it done a little differently; in KRunner you input say `100 USD` and get a result in all currencies of your interest (EUR, GBP, ...), so it's in general a more open approach.

Just shouting into the void, it's fine if that way of functioning is not the main idea behind this plugin :)

**Comment by mmshivesh** [comment]
@tMaxx You can set this plugin up in the same way in case that's what you desire, assuming I'm not misunderstanding what you're looking for:

![image](https://github.com/Advaith3600/PowerToys-Run-Currency-Converter/assets/23611514/725c2aca-cf9d-49e9-9b88-c1a6d91b1608)

This works as long as you  set the "currencies of your interest" in the settings, and check the box to include in Global Result

![image](https://github.com/Advaith3600/PowerToys-Run-Currency-Converter/assets/23611514/c7033913-83d8-4117-89d4-ff07691ff16a)

**Comment by soukamoshirenai1** [comment]
quite sure it's already doing that, an input can be shown in two currencies.

![image](https://github.com/Advaith3600/PowerToys-Run-Currency-Converter/assets/86631555/c29c73bc-1647-44b8-96f8-51ba022406e7)

**Comment by AstudilloMarillo** [comment]
> i'm quite sure it's already doing that given that an input can be shown in two currencies.
> 

Yes, but not for all currencies when you have a whole list filled in the extra currencies field.

**Comment by Advaith3600** [comment]
@AstudilloMarillo I am just curious, are you able to see both conversions at the same time right? Like this:

![image](https://github.com/Advaith3600/PowerToys-Run-Currency-Converter/assets/21041099/3ee99b81-d65a-4361-a846-3d8446111593)

The plugin currently lists `local -> global`, `local -> extra`, `global -> local` and `global -> extra` by default.

The reason why I am asking this is, the whole idea of an on the fly inversion of direction seems bit too niche, idk, and personally I don't see myself using that functionality. And if the reason why you are asking for that is because you can't see both conversions, then there is not need for this. I would add this functionality if you still need it, because it won't harm anything else.

**Comment by AstudilloMarillo** [comment]
_I can see how you think it's niche. I still feel like for me, it makes sense. Yes, right now I can see both way conversions, but not of the same currency vs all the currencies I have in Extra. Putting the same currency in Global as you have in Local is no use, and putting a different currency in Global only gives access to 1 inverted conversion, the other results are completely unrelated to the Local currency._

_On-the-fly convertion would make it so I'd never have to put in (or remember) any currency acronym._

_Alternatively, having an option to set the Quick Convertion Direction to 'Both' would also be a good solution._ 

----

Writing this now, I realize that I think I misrepresented my own idea. By default I have the convertion set to 'from Local to Global', but in my mind that meant 'from Local to Extra' (I don't use Global). And inverting that would then result in 'from Extra to Local'. But trying it out I realize now that's not what it would do, it would only do Global and not the Extra currencies. 

I made 2 mockups to represent my ideas. Number 1 is a result if there was an option in the Quick Convertion 'from Extra to Local' that could be accessed using on-the-fly invertion with !:
![image](https://github.com/Advaith3600/PowerToys-Run-Currency-Converter/assets/136191659/9a3440ab-25e7-4653-a1ff-dd68be2ab489)

And this second one is a mockup of a result if there was a Quick Convertion option 'from Local to Extra & from Extra to Local':
![image](https://github.com/Advaith3600/PowerToys-Run-Currency-Converter/assets/136191659/6ac05a3b-bc16-4cc8-8a2d-e46fa41423de)

If you look at these and think "this makes no sense" then maybe my idea is just not that great in the end. I personally get excited by the prospect of being able to use it like this. Either of these methods would be fine for me.

**Comment by Advaith3600** [comment]
Sorry for the late reply, the on-the-fly conversion doesn't seem that logical to me at this point due to the introduction of extra currencies as people won't get which way is the inversion.

 I was thinking of another way to do this using toggles that list `extra -> local` and `extra -> global` respectively. This would make it clear that these results are not added by default and on checking it, the conversions will be shown along with the default.

**Comment by AstudilloMarillo** [comment]
At this point, I think I'm just gonna conform to the functionality you'll implement. The plugin is already great, so if your implementation of this request benefits me that's great, and otherwise it's also fine. 🙂

**Comment by Advaith3600** [comment]
Hey, I have made some changes, please try the following and let me know your feedback.

[CurrencyConverter-1.1.2-x64.zip](https://github.com/Advaith3600/PowerToys-Run-Currency-Converter/files/15258840/CurrencyConverter-1.1.2-x64.zip)

**Comment by Advaith3600** [comment]
It's not an issue, I was busy with all the moving, otherwise, I would have finished this earlier. Keep your ideas coming, these are useful even for me. I will release the new version soon.
