### ISSUE TITLE
Quick conversion is confusing when I've added an 'extra currency'

### ISSUE THREAD

**Issue by untitled500** [Advaith3600/PowerToys-Run-Currency-Converter#6]
Assuming the intent of converting something quickly is to convert from a home curency (SGD in this example) to other currencies (USD, EUR in this example):
It gets confusing when I see 13.77 EUR and 18.63 EUR. I need to spend a minute or more to see which direction and what amount is being converted.

MacOS does it well: https://techstacker.com/static/1785b23e59320ecd54efe14e0880a579/bfdc0/mac-spotlight-search-currency-conversion.png

Current UI (ignore the red box):
![Untitled](https://github.com/Advaith3600/PowerToys-Run-Currency-Converter/assets/59500937/de180890-f25d-469c-8a00-62409635efff)

**Comment by Advaith3600** [comment]
Hey, unfortunately, windows powertoys run doesn't give many options to change the UI of the output, therefore we are stuck with such text-based outputs. I also prefer the way some applications on Mac do it, especially Raycast:

<img width="791" alt="image" src="https://github.com/Advaith3600/PowerToys-Run-Currency-Converter/assets/21041099/ad9e2623-b41c-4a0d-a700-2f8a9824871b">

The plugin is built in such a way that the order in which this is shown is predictable:
1. Local to Global
2. Local to Extra
3. Global to Local
4. Global to Extra
5. Extra to local (coming soon - optional)
6. Extra to global (coming soon - optional)

Plus the global is an optional field that will remove unnecessary conversions if you do not want it.

**Comment by untitled500** [comment]
Yeah Raycast does it well too. I assume all Powertoys lets you do is to send plain text and subtext and one icon as output. I suggest something like this:
USD 30 = INR 2501.42
USD 30 = SGD 40.48

Bonus of doing so - is to eliminate confusion in the existing tool where I type 30 USD and it shows 22 USD Currency conversion from SGD to USD.
![Untitled](https://github.com/Advaith3600/PowerToys-Run-Currency-Converter/assets/59500937/9e3b0a9a-ef47-446a-9cc8-f8635335c2c6)


Also, why the distinction between Global and Extra? Can I have multiple comma separated Globals instead? That would make some things easier?
1. Local to Global1
2. Local to Global2
3. Global1 to Local
4. Global2 to Local

**Comment by Advaith3600** [comment]
That indeed makes sense, thanks for the idea, I will do some changes

**Comment by Advaith3600** [comment]
I have made some changes, please try the following and let me know your feedback.

[CurrencyConverter-1.1.2-x64.zip](https://github.com/Advaith3600/PowerToys-Run-Currency-Converter/files/15258849/CurrencyConverter-1.1.2-x64.zip)

**Comment by untitled500** [comment]
I like the output style setting. Works well for someone who is familiar with the existing style, and will work for new users like me. May I suggest Full Text as the default output style for new users. Also, there is a spelling mistake for Conversion -- in "Quick Convertion Direction" and "Quick Convertion Local Currency".
