### ISSUE TITLE
Enhancement: Support both Prefix and Suffix

### ISSUE THREAD

**Issue by untitled500** [Advaith3600/PowerToys-Run-Currency-Converter#8]
Some websites display currencies as "EUR 1" instead of 1 EUR. The suggestion here is to support "eur 1" and "eur 1 to usd" for ease of use.

**Comment by Advaith3600** [comment]
This has been on my todo list for a long time, this seems to be the perfect time to do it. You can expect it to drop in a couple of days.

**Comment by Advaith3600** [comment]
[CurrencyConverter-1.1.4-ARM64.zip](https://github.com/Advaith3600/PowerToys-Run-Currency-Converter/files/15469019/CurrencyConverter-1.1.4-ARM64.zip)
[CurrencyConverter-1.1.4-x64.zip](https://github.com/Advaith3600/PowerToys-Run-Currency-Converter/files/15469020/CurrencyConverter-1.1.4-x64.zip)

This feature has been added, I am not releasing this version yet as I am still testing different parts.

**Comment by Advaith3600** [comment]
This version has been released now.
