### ISSUE TITLE
Custom aliases + more currencyies

### ISSUE THREAD

**Issue by iSplasher** [Advaith3600/PowerToys-Run-Currency-Converter#9]
Hi, would it be possible to add the following things?
- Load "currencies.json" from a local file. It can just be inside the plugin folder
- Support aliases. I keep typing `EURO` or `EU` and always forget it's `EUR`. Would be nice if I could add my own aliase to some of the currencies. Or maybe just support fuzzy search on the current ones.

Thanks!

**Comment by Advaith3600** [comment]
Hi, these look like some nice additions—one of the issues with a local currencies.json file will be that it will be outdated and it will be up to the users to update it. Aliasing is an idea that I wanted to do from day one, but always messed up while implementing it. 

Could someone help with implementing these functionalities? In the meantime, I will try coming up with a simple approach.

**Comment by Steef-Broeder** [comment]
Hi, I would like to try and add something like this. I have little experience with cs and contibuting to open source but I will try this coming week!

**Comment by Advaith3600** [comment]
I have come up with a solution to this issue, please check the following and let me know if it is having any problem or missing any feature. You can read more about the config [here](https://github.com/Advaith3600/PowerToys-Run-Currency-Converter/tree/alias?tab=readme-ov-file#aliasing)

[CurrencyConverter-1.2.0-x64.zip](https://github.com/user-attachments/files/16690072/CurrencyConverter-1.2.0-x64.zip)
[CurrencyConverter-1.2.0-ARM64.zip](https://github.com/user-attachments/files/16690073/CurrencyConverter-1.2.0-ARM64.zip)
